### ISSUE TITLE
Using mmoitems in item paywalls

### ISSUE THREAD

**Issue by PiglerthePig** [rockyhawk64/CommandPanels#100]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
No

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
It is not related to a problem.

### Describe the solution you'd like
Implement the use of mmoitems in item paywalls

### Describe alternatives you've considered
I have not really considered any other alternatives, i do not wish to install another plugin just for crafting with a bad inventory ui, because command panels is perfect for what i am aiming for in my server.

### Additional context
This one feature can be used as custom crafting station superior to that of mmoitems' one, with the ability to create a fancy ui, with other elements inside, like a "go back" button, which mmoitems did not implement.

**Comment by rockyhawk64** [comment]
This feature already exists. This is an example:
```YAML
panels:
  template:
    perm: default
    rows: 1
    title: '&8Template Panel'
    custom-item:
      dagger1:
        material: mmo= DAGGER DRACULA_DAGGER
      '4':
        material: COBBLESTONE
        stack: 1
        name: '&aSell Dracula Dagger'
        commands:
        - item-paywall= dagger1
        - msg= sold dracula dagger
```
