### ISSUE TITLE
Panel variables crashing the server on 3.15.4.0

### ISSUE THREAD

**Issue by fireFerry** [rockyhawk64/CommandPanels#118]
### Describe the bug
If you use a setup like this:
```
panels:
  madera:
    perm: default
    rows: 6
    title: '&0&lMadera'
    item:
      '2':
        material: ARROW
        stack: 1
        name: '&4Test1'
        commands:
        - open= test1 [%cp-nom%:%cp-player-online-1-find%]
  test1:
    perm: default
    rows: 6
    title: 'Test1'
    item:
      '2':
        material: ARROW
        stack: 1
        name: '&4Test1 sub1'
        commands:
        - open= test2 [%cp-nom2%:%cp-nom%]
  test2:
    perm: default
    rows: 6
    title: 'Test2'
    item:
      '2':
        material: ARROW
        stack: 1
        name: '&4Test1 sub 2'
        lore:
        - 'value: %cp-nom2%'
        commands:
        - 'msg= %cp-nom2%'
```
will crash the server, this only happens on the newest cp version.
### To Reproduce
1. Create a panel with panel variables
2. Try opening the panels, and the server will crash.

### Expected behavior
It should just pass through correctly like with the older versions

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
--------------------------
### Versions:
 - Minecraft: 1.16.5 paperspigot
 - CommandPanels: 3.15.4.0
