### ISSUE TITLE
Potion formatting for buy commands results in uncraftable potions.

### ISSUE THREAD

**Issue by NotGolden** [rockyhawk64/CommandPanels#130]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?

Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?

Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*

Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

Yes

### Describe the bug

I have been trying to format a buy command message to allow my players to purchase potions from a command panel. The format I am using is correct. Being (buy= 500 POTION 1 potion:HEAL) This particular format (potion:HEAL) is also the example format on the wiki. When I buy the potion using the panel, it gives me an uncraftable potion every time. This is either a bug or I am not doing something correctly. I havent had much success asking about this on the discord.

### To Reproduce
1. Create a command panel
2. Set the command of an item as "buy= 500 POTION 1 potion:HEAL"
3. Receive an uncraftable potion instead of a potion of healing.

![unknown-41](https://user-images.githubusercontent.com/33296840/119431649-f2f87f00-bce0-11eb-8e01-4f67f18aa363.png)

(in this image I tried the ID for a harming potion. Also resulting in an uncraftable potion upon command execution.)

### Expected behavior

The command panel would close like normal and give the player a potion (in this case a potion of healing) while taking out $500 from their economy account. In this case, the correct amount of money is taken, but the player is given an uncraftable potion instead of what I specify in the command by item id.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

I have attached one image above in the reproduce the error section.

### Versions:
 - Minecraft: [1.16.2]
 - CommandPanels: [3.15.5.4]

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

N/A

**Comment by rockyhawk64** [comment]
The potion type `HEAL` is for an older version of Minecraft, you will need to check on the Spigot page for your version https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html
In your case, it would be `INSTANT_HEAL`.

Using potion:HEAL is only on the sell= tag, I didn't add an explanation to the buy= tag. Instead, you need to do something like this:
```YAML
panels:
  template:
    perm: admin
    rows: 1
    title: '&8Template Panel'
    empty: GLASS_PANE
    custom-item:
      potion1example1:
        material: POTION
        potion: INSTANT_HEAL
    item:
      '4':
        material: COBBLESTONE
        stack: 1
        name: '&fClick Me!'
        commands:
        - paywall= 10
        - give-item= potion1example1
```
Make a custom item that contains the heal potion type and then give the player the item. This way it can have custom names and other customizations, in my example above, it costs $10 for the potion.
