### ISSUE TITLE
Option " %cp-player-input- [number]% " does not work

### ISSUE THREAD

**Issue by isJ3ff** [rockyhawk64/CommandPanels#148]
Option " %cp-player-input- [number]% " does not work

I have tried every possible way and it has not worked for me

Sorry for my English I use the translator

**Comment by rockyhawk64** [comment]
Here is an example:
```YAML
'0':
        material: NAME_TAG
        stack: 1
        name: '&6&lClick Me'
        lore:
        - '&6Click'
        player-input:
        - msg= you typed %cp-player-input-1%
        commands:
        - cpc
```
