### ISSUE TITLE
Custom Model Data not working

### ISSUE THREAD

**Issue by olix3001yt** [rockyhawk64/CommandPanels#15]
**Describe the Issue**
I'm trying to create menu to choose item skins, but custom model data doesn't work

**Expected behavior**
Fix

**Screenshots**
not needed

**Versions:**
 - Minecraft: 1.16.1
 - CommandPanels: 3.2.3

**Comment by fireFerry** [comment]
Hi, I need the panel before I can help you!

**Comment by olix3001yt** [comment]
Hi, my panel is empty panel with one sword. My problem is when I try to add custom model data using GUI editor it doesn't change config.

**Comment by fireFerry** [comment]
What do you mean by custom model data? Do you just drag an item in with nbt tags?

**Comment by olix3001yt** [comment]
No, when I shift right click on item in GUI editor there is option to change it

**Comment by fireFerry** [comment]
What custom model data are you trying to add?

**Comment by olix3001yt** [comment]
1

**Comment by rockyhawk64** [comment]
Can you send the yml file that is in the panels folder, of the specific panel.

**Comment by olix3001yt** [comment]
```
panels:
  skins:
    perm: default
    rows: 4
    title: '&6Skins'
    command: skins
    sound-on-open: BLOCK_NOTE_BLOCK_CHIME
    empty: BLACK_STAINED_GLASS_PANE
    item:
      '0':
        material: DIAMOND_SWORD
        name: Fire Skin
```
