### ISSUE TITLE
Has Section Improvements & Ideas

### ISSUE THREAD

**Issue by Maroon28** [rockyhawk64/CommandPanels#159]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes
### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
Yes. While the current `has` section system is great, and does its job excellently, it's a massive pain to work with when building out complex panels with lots of checks and values. The files just get uncontrollably long, spanning over thousands of lines. It makes maintaining the panel, or changing it a lot more difficult. 

### Describe the solution you'd like
A way to merge multiple values into 1 line (or multiple). This feature would be especially handy in items that are the exact same, but with only the check being the difference. We could use something similar to Java's operators. || (OR), && (AND) for this idea. Here's a quick example:

```yaml
hasvalue:
     value: '1 || 2'
     compare: '%money%'
     output: true
     material: GREEN_WOOL
     name: 'Your balance is either 1 or 2!' 
```

That's one way to do it, but we can get a lot crazier with the syntax. For the && operator, we obviously can't use one placeholder and expect two values, so we could most likely implement something similar with _weighing_ the values and compares. Take a look:
```yaml
hasvalue:
     value: '1'
     compare: '%money%'
     value0: '100'
     compare0: '%exp%'
     material: GREEN_WOOL
     name: 'Your balance is 1, and your exp is 100!'
```     
Maybe we can also introduce an `operator:` section? You specify there what type of operator you want to use (either OR or AND) , and it could default to AND. This would allow more flexibility with the OR operator instead of the example above! Such as this:

```yaml
hasvalue:
     operator: 'OR'
     value: '1'
     compare: '%money%'
     value0: '100'
     compare0: '%exp%'
     material: GREEN_WOOL
     name: 'Your balance is 1, or your exp is 100!'
```

So, what are y'alls thoughts about this? I feel like it's much cleaner to do it this way, as I only had to write  2 extra lines, instead of needing to make a whole new has section. This example is pretty small, but for most panels there'd be lots of lore lines, commands, and possibly more stuff. So you can imagine how big stuff gets and how quick it gets there.

**Comment by Teric7** [comment]
I would like to request the same feature.

**Comment by rockyhawk64** [comment]
An update on progress. All three of the above ideas are in progress, however not in the exact same way. Take the bottom example you sent that looks like this:
```YAML
hasvalue:
  operator: 'OR'
  value: '1'
  compare: '%money%'
  value0: '100'
  compare0: '%exp%'
  material: GREEN_WOOL
  name: 'Your balance is 1, or your exp is 100!'
```
This is how it will actually look:
```YAML
hasvalue0:
  value0: '1'
  compare0: '%money% OR'
  value1: '100'
  compare1: '%exp%'
  material: GREEN_WOOL
  name: 'Your balance is 1, or your exp is 100!'
```
As you can see I have added a 0 to the end of the hasvalue and at the end of the value/compare. This is because they all will require a number, even the first one. 
There will also be a new has section, it is an improved section that takes all of the original sections and combined them. HasPerm, HasValue and HasGreater have been combined into a section called Has. (you can now use all 4 of them)

**Benefits of using 'Has' instead of the other sections**
Let's say you had this originally:
```YAML
hasperm0:
  value0: gamemode.creative
  material: BARRIER
  hasgreater0:
    value0: 3
    compare0: 4
    material: GREEN_WOOL
```
you can now combine both the HasPerm and HasGreater sections into one section, doing this:
```YAML
has0:
  value0: '%cp-player-name% HASPERM'
  compare0: 'gamemode.creative OR'
  value1: '4 ISGREATER'
  compare1: '3'
  material: GREEN_WOOL
```
Essentially if you read the has section from left to right, it will be something like this: `RockyHawk has perm gamemode.creative or 4 is greater 3
`
