### ISSUE TITLE
Simple button 

### ISSUE THREAD

**Issue by ShazadSkriptREPO** [rockyhawk64/CommandPanels#173]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I want to use skript with command panel but i need to make something like button without perms or placeholders. 

### Describe the solution you'd like

I would like to see something like button (white wool) and when its clicked it turns red and then when its clicked one more time it Goes white one more time.. 
Like On and Off switch with would ALLOW me to make use of drop disable and drop enable, and would make me write in lore of wool state if drop is enabled or not.  Right now its not possible to make it without use od placeholders or permissions witch i dont want to use or even cant. 

### Describe alternatives you've considered

None 

### Additional context

Nope

**Comment by Maroon28** [comment]
You can use cpdata to make this work. Here's a rough example

```yaml
   has0:
     value0: 'true'
     compare0: '%cp-data-toggled%'
     material: GREEN_WOOL
     name: 'This is toggled!'
     commands:
     - set-data= toggled false
   has1:
     value0: 'false'
     compare0: '%cp-data-toggled%'
     material: RED_WOOL
     name: 'This is not toggled!'
     commands:
      - set-data= toggled true
```
