### ISSUE TITLE
Make the OR operator compare more than just two values

### ISSUE THREAD

**Issue by Maroon28** [rockyhawk64/CommandPanels#177]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
Yes, the OR operator is a little bit limited at the moment. It compares two values, which stuns a lot of creativity. It should be able to compare potentially infinite (like the AND). Here's an example:
         
### Describe the solution you'd like
``` 
        has0:
         value0: 'yes'
         compare0: '%checkitem_inhand,matcontains:SWORD% OR'
         value1: 'yes'
         compare1: '%checkitem_inhand,matcontains:AXE% OR'
         value2: 'yes'
         compare2: '%checkitem_inhand,matcontains:SHOVEL% OR'
         value3: 'yes'
         compare3: '%checkitem_inhand,matcontains:HOE%'
         value4: 'yes'
```  

Here, I only want to check if the item in hand is either a sword, axe, shovel, or hoe. You can already do this by making a dedicated has section for each single item, but I personally think that goes against the whole point of the 3.17.0 update, as it doesn't give a whole lot of room for panel optimisation. 

### Describe alternatives you've considered
Making a has section for each item in the list, but once again this makes the panels go out for way too long, especially when you have more items to compare.

**Comment by rockyhawk64** [comment]
The OR operator works differently from the AND operator. Try this:
```YAML
'4':
        material: BARRIER
        name: Barrier
        has0:
          value0: '%checkitem_inhand,matcontains:SWORD% OR %checkitem_inhand,matcontains:AXE% OR %checkitem_inhand,matcontains:SHOVEL% OR %checkitem_inhand,matcontains:HOE%'
          compare0: 'yes'
          material: GRASS_BLOCK
```
