### ISSUE TITLE
#Commands

### ISSUE THREAD

**Issue by Aadi-mone** [rockyhawk64/CommandPanels#180]
Best Plugin!
Can you add a command which can disable a certain block or item for a period of time.
example:
/cpitemdisable or /cpi
/cpi (panelname) (itemnumber) (time for disable in seconds)
Hope you'll add it :)

**Comment by fireFerry** [comment]
Hello,

Please actually use our template provided instead of clearing it. It seems like you want to have cooldowns on the items in the panel, but this is already doable, a video tutorial here: https://youtu.be/GgNtKG3fSO8.

**Comment by Aadi-mone** [comment]
well i don't need cooldowns i want to delete or disable a item for some time
and is there a command to edit a command for an item in game? for a panel?

**Comment by fireFerry** [comment]
Disabling an item for some time is what we define as a cooldown, and disabling an item in a panel is also already possible using has sections: https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/item-sections.

**Comment by Aadi-mone** [comment]
is it possible with commands?

**Comment by fireFerry** [comment]
With commands and has sections, this is possible. If you'd like to have direct support, please join the Discord server: https://discord.io/commandpanels

**Comment by Aadi-mone** [comment]
**Ok, I used sections, and I wanted to players not to use item 10.
but players who have the permission node mycmd.cmd.bedwar shd be able to do that,
but here players having and not having can enter that server :/ 
and this is how my panel config looks:** 
```yml
item:
      '10':
        material: red_bed
        stack: 1
        name: '&6&l&e● &a&lBedwars &6&l&e● &7(&6%playerlist_online,world,yes,amount,bedwars_arena+bedwars+bedwars_5+bedwars_2+bedwars_3+bedwars_4%/20&7)'
        has1:
        value1: '%cp-player-name% HASPERM'
        compare1: mycmd.cmd.bedwar
        lore:
        - '&b&m--------------------------'
        - '&8Version 1.16.5'
        - '&8> &aClick to connect.'
        - '&8> Online Players: &7(&6%server_online_bedwars%/20&7)'
        - '&b&m--------------------------'
```
