### ISSUE TITLE
=> data for a command tag

### ISSUE THREAD

**Issue by jman13378** [rockyhawk64/CommandPanels#196]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes/

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
yes, on our server we have a playtime rewards panel and if they miss a day they lose their streak so if they do it resets to 1 and sets their lastplaytimestreak data to the failed streak and with this tag i want to make a high score system
### Describe the solution you'd like
a command tag for cp data so like `greater-data=` and `isgreater-data=` so they can check is the players data is greater if not then it acts like a `add-data=` or make them in the following format `<greater|isgreater>-data= <data> [player] <compared data> [data] [command|data] <command (command can includes command tags)> <data (a new data to set)>`
### Describe alternatives you've considered
has section for data but if you have this it would save space in your yml file
### Additional context
no

**Comment by rockyhawk64** [comment]
From my understanding, this is how I would do that with features that have already been added into CommandPanels
```YAML
'4':
        material: DIRT
        name: 'Not Enough'
        has0:
          value0: '%cp-data-lastplaytimestreak% ISGREATER'
          compare0: '10'
          name: "&7Click Me"
          lore:
          - "&8Click this to"
          - "&8perform any command"
          - '&8because you have 10 or more'
          commands:
          - msg= Command Clicked
          - msg= This command will only run if you have 10 or more lastplaytimestreak
          material: SLIME_BALL
```
