### ISSUE TITLE
Log feature for commands and console tag

### ISSUE THREAD

**Issue by jman13378** [rockyhawk64/CommandPanels#198]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
Just to track what a player executes
### Describe the solution you'd like
So mycommand[MyCommand](https://dev.bukkit.org/projects/mycommand/pages/configuration-and-example)  have a feature like this

```
It's now possible save logs text in separate log file. Just use log_filename: "filename.log" like the exampel here below, and the $log$ message will get saved in "/plugin/MyCommand/logs/filename.log"

my_custom_logger:
 command: /mylog
 type: RUN_COMMAND
 runcmd:
  - "$text$&aThis log file is getting saved in &2/MyCommand/logs/filename.log"
  - "$log$[$player] $multiargs"
 log_filename: filename.log
```

### Describe alternatives you've considered
None
### Additional context
![Screenshot_20220325-090717_Chrome](https://user-images.githubusercontent.com/101841938/160126422-7e10771b-505e-44e9-83b5-d0cf29516b53.jpg)
![Screenshot_20220325-090644_Chrome](https://user-images.githubusercontent.com/101841938/160126426-754a0e28-8ad9-4d55-b36a-9e340b82b1fe.jpg)
