### ISSUE TITLE
%cp-player-input% usage is not listed in the wiki, and proper use of %cp-player-input% is not accessible in-game 

### ISSUE THREAD

**Issue by BeekrBonkr** [rockyhawk64/CommandPanels#205]
**Previously, click commands with a player input in a gui could be formatted like so:**

_op= ban %cp-player-input%_

**This could be done in game or in the panel yml file like so:**

```
      '9':
        material: GOLDEN_SWORD
        name: '&6&lBan Player'
        stack: 1
        commands:
        - msg= &f&lWho is getting the ban hammer?
        - ban %cp-player-input%
```

Now, however, functionality for setting up player text inputs in game has been lost, and the wiki has not been updated with the correct information.

This is the new formatting:

```
      '9':
        material: GOLDEN_SWORD
        name: '&6&lBan Player'
        stack: 1
        player-input:
        - ban %cp-player-input%
        commands:
        - msg= &f&lWho is getting the ban hammer?
```
  
  There should be an in game way to do this or at least the wiki should be updated with the correct info.
