### ISSUE TITLE
Has Sections

### ISSUE THREAD

**Issue by KINGGAMER096** [rockyhawk64/CommandPanels#225]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
No

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Expected behavior
https://user-images.githubusercontent.com/97855007/184257362-312ad66f-228b-4ca1-9be3-ab8476178c4e.mp4

### Versions:
- Minecraft: [e.g. 1.16.5]

**Comment by jman13378** [comment]
you can try this
```
panels:
  panel-1:
    perm: default
    rows: 3
    title: '&8Generated panel-1'
    empty: BLACK_STAINED_GLASS_PANE
    custom-item:
      itemThree:
        material: SUNFLOWER
        name: 'item'
        lore:
        - 'This is the lore!'
        enchanted: true
    item:
      '0':
        material: AIR
        itemType:
        - placeable
        - removeItem
        stack: 1
        name: ''
      '1':
        material: RED_STAINED_GLASS_PANE
        stack: 1
        name: ''
        has0:
          value0: '%cp-identical-itemThree,0%'
          compare0: 'true'
          material: GREEN_STAINED_GLASS_PANE
```

**Comment by KINGGAMER096** [comment]
ok i well try

**Comment by KINGGAMER096** [comment]
but i want the play to click the item in their inventory then the item remove from the players inventory then place it in the gui and when the player close the gui the item come back to them!

**Comment by jman13378** [comment]
does the item not come back?

**Comment by KINGGAMER096** [comment]
no!

**Comment by KINGGAMER096** [comment]
![image](https://user-images.githubusercontent.com/97855007/184258885-9d96cee7-bfb6-4cc7-9279-10beaba5e447.png)
can i know what is the %0 for??

**Comment by jonjon1322** [comment]
% is the end of the placeholder and 0 is the slot #

**Comment by KINGGAMER096** [comment]
oh thx

**Comment by KINGGAMER096** [comment]
ummm ok

**Comment by KINGGAMER096** [comment]
how do i make the panel when i close it the item i put in come back to me?

**Comment by jman13378** [comment]
the only problem is that other players can take the item bc it will drop on the ground
itemType:
- placeable
- dropItem

**Comment by KINGGAMER096** [comment]
is ther any way to put the item back to players inventory??

**Comment by jman13378** [comment]
itemType:
- placeable
- removeItem

**Comment by KINGGAMER096** [comment]
```
panels:
  Upgrade:
    perm: default
    rows: 3
    title: '&8Generated panel-1'
    empty: BLACK_STAINED_GLASS_PANE
    custom-item:
      itemThree:
        material: WOODEN_PICKAXE
        name: 'Woodin Pickaxe [0]'
        lore:
        - 'This is the lore!'
        enchanted: true
    item:
      '0':
        material: AIR
        itemType:
        - placeable
        - removeItem
        stack: 1
        name: ''
      '1':
        material: RED_STAINED_GLASS_PANE
        stack: 1
        name: '&fclose'
        has0:
          value0: '%cp-identical-itemThree,0%'
          compare0: 'true'
          material: GREEN_STAINED_GLASS_PANE
          stack: 1
          name: '&fopen'
```
why whean i place the item in game the red_stained_glass_pane dont change
