### ISSUE TITLE
CommandPanels improperly parsing random placeholders as "null"

### ISSUE THREAD

**Issue by Sixsoul** [rockyhawk64/CommandPanels#234]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.18

### What CommandPanels version are you using?

3.18.1.2

### What server software are you running?

PaperMC

### What happened?

Have been having a weird issue where some placeholders return "null" despite working when I /papi parse them. Here is an example that I am having an issue with:
```
'16':
        material: COOKED_BEEF
        customdata: 10004
        name: '&6Daily Farming'
        lore:
        - "&f"
        - "&7Harvest 125 of any crop in any"
        - "&7of the adventure worlds."
        - "&7"
        - "&7Rewards:"
        - "&8 - &f&f125"
        - "&8 - &f&f50"
        - "&7"
        - "&7Progress: &6%quests_quest:DailyFarming_task:task1_progress%&7/125 crops harvested"
        has0:
          value0: 'NOT 0'
          compare0: '%quests_quest:DailyFarming_cooldown%'
          material: PAPER
          customdata: 10100
          name: "&aQuest Completed"
          lore:
          - "&7You've already completed this"
          - "&7quest today!"
          - "&7"
          - "&7Cooldown: &a%quests_quest:DailyFarming_cooldown%"
```
So when I open this gui, it is displaying the has0 material/display/lore even though I have it set to NOT 0 for %quests_quest:DailyFarming_cooldown% and when I papi parse %quests_quest:DailyFarming_cooldown% it does in fact return 0. Additionally, where I have that same placeholder in the lore it says "null".

I have 6 other buttons in this GUI configured EXACTLY the same way and those are working. So I don't understand why this one button doesn't work? I have another similar issue with a different GUI where 1/6 buttons are messed up in the same way too, so I'm led to believe it is an issue with CommandPanels.

### Steps to reproduce the issue

You'd need the Quests plugin to reproduce the issue, but you could just copy and paste the configuration I pasted above to try and recreate the issue.

### Expected behavior

Placeholders within CommandPanels should parse without issue, especially when being used for a has condition.

### Screenshots/Videos (you can drag and drop files or paste links)

https://streamable.com/apy4sk
