### ISSUE TITLE
HAS sections for the title

### ISSUE THREAD

**Issue by SebyRo23** [rockyhawk64/CommandPanels#236]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

```
title:
  title: "Your username is not RockyHawk" 
  has0:
    value0: RockyHawk
    compare0: '%cp-player-name%'
    title: "Your username is RockyHawk"
    has0:
      value0: '%cp-player-name% HASPERM'
      compare0: 'gamemode.creative'
      title: "Your username is RockyHawk AND you can do /gamemode"
  has1:
    value0: '%cp-player-name% HASPERM'
    compare0: essentials.fly
    title: "Your username is RockyHawk AND you can do /fly"
```

### Describe the solution you'd like

HAS sections for the title

### Describe alternatives you've considered

There are no features like this for the title
