### ISSUE TITLE
Player can't sell item from MMOItems plugin

### ISSUE THREAD

**Issue by NeotenySS** [rockyhawk64/CommandPanels#237]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your issue is a duplicate and your problem already has been solved?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### What server version are you running?

1.19

### What CommandPanels version are you using?

3.18.2.0

### What server software are you running?

Spigot

### Describe the Issue

I couldn't find a solution to the problem.
The player must sell the item from the plugin MMOItems and get the money.
The plugin can not buy an item from the player and writes: item not found.

### Expected behavior

You added support for NBT and MMOItems, but the mmo= function can only be used if the player wants to buy something, but not sell it.
Support doesn't know the solution, they're just guessing, but updating the Wiki for such cases would make it much easier, as I very often see people contacting Discord with this issue.

### Additional context/Panel files

This is the simplest of many examples.
panels:
  ooo:
    perm: default
    rows: 1
    title: test
    commands:
    - ooo
    sound-on-open: BLOCK_ANVIL_STEP
    empty: FERMENTED_SPIDER_EYE
    panelType:
    - unmovable
    custom-item:
      test:
        material: RED_WOOL
        customdata: 99999
        nbt:
          name: Apples
        name: '&7Apples'
    item:
      '6':
        material: RED_WOOL
        name: '&cNO'
        commands:
        - cpc
      '1':
        material: RED_WOOL
        customdata: 99999
        name: '&7Apples'
        commands:
        - item-paywall= test
        - console= give money %cp-player-name% 10

### Screenshots/Videos (you can drag and drop files or paste links)

I looked at your code in ItemCreation.java
I saw that nbt support is added by the method
if(addNBT){
                s = plugin.nbt.setNBT(s);
s = plugin.nbt.setNBT(s,key,itemSection.getString("nbt." + key));

I tried doing this configuration in the panel, but it didn't work.
Example:

This is the simplest of many examples.
panels:
  ooo:
    perm: default
    rows: 1
    title: test
    commands:
    - ooo
    sound-on-open: BLOCK_ANVIL_STEP
    empty: FERMENTED_SPIDER_EYE
    panelType:
    - unmovable
    custom-item:
      test:
        material: RED_WOOL
        customdata: 99999
        nbt:
          MMOItems.nbt.MMOITEMS_ITEM_ID: Test
        name: '&7Apples'
    item:
      '6':
        material: RED_WOOL
        name: '&cNO'
        commands:
        - cpc
      '1':
        material: RED_WOOL
        customdata: 99999
        name: '&7Apples'
        commands:
        - item-paywall= test
        - console= give money %cp-player-name% 10

**Comment by rockyhawk64** [comment]
Everything can be found in the Wiki https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki/panel-editing/panel-settings#custom-items, searching through code shouldn't be necessary to find features.

Make a custom item that contains the MMO item and then sell the custom item.

```YAML
panels:
  test:
    perm: default
    rows: 1
    title: '&8Test Panel'
    custom-item:
      example_mmo:
        material: mmo= DAGGER STEEL_DAGGER
    item:
      '4':
        material: DIAMOND
        name: "&5Sell Steel Dagger"
        commands:
        - item-paywall= example_mmo 1
        - msg= you have sold the item, have $5
        - console= eco give %cp-player-name% 5
```
