### ISSUE TITLE
MMOItems allowed in item-paywall

### ISSUE THREAD

**Issue by Sixsoul** [rockyhawk64/CommandPanels#256]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

It's a little wonky getting any sort of custom items working with an item paywall, especially for servers with MMOItems heavily integrated.

### Describe the solution you'd like

Allow us to use the mmoitems tag in line with the item-paywall tag. Like:
`- item-paywall= mmo= SWORD WOODEN_SWORD`

### Describe alternatives you've considered

There really isn't an alternative, I feel like this functionality would greatly improve the plugin.

**Comment by rockyhawk64** [comment]
This can be done by using a custom item:
```YAML
panels:
  test:
    perm: admin
    rows: 2
    title: '&8Template Panel'
    custom-item:
      mmoItem1:
        material: mmo= SWORD WOODEN_SWORD
    item:
      '4':
        material: cps= Porkchop_64
        stack: 1
        name: '&fExample Item!'
        commands:
          - item-paywall= mmoItem1
          - msg= sold mmo item
```
