### ISSUE TITLE
Fetching Player Skins for Heads is Incredibly Laggy

### ISSUE THREAD

**Issue by Sixsoul** [rockyhawk64/CommandPanels#260]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

3.19.0.3

### What server software are you running?

PaperMC

### What happened?

Made a panel with 18 player heads that parse placeholders to set the skin, opening it sometimes drops my TPS by 1-10, sometimes it crashes it entirely.

### Steps to reproduce the issue

Create a panel with a few heads that parse papi placeholders to set their material. Open the panel and watch your server lock up.

### Expected behavior

Should be able to use heads freely without worrying about this, though I'm not sure how it can be resolved.

### Screenshots/Videos (you can drag and drop files or paste links)

Timings: https://timings.aikar.co/dev/?id=7614565c288840bcbd9e3af4a072bfea

**Comment by jman13378** [comment]
can you send that panel

**Comment by TinyTank800** [comment]
Also please make sure you have listed your correct command panels version as there are many updates past the one you have listed. /cpv

**Comment by jman13378** [comment]
Also it seems like your using `git-Pufferfish-68 (MC: 1.19.4)` ![image](https://github.com/rockyhawk64/CommandPanels/assets/101841938/45d08913-c107-4308-bd00-ca7f3dba743c)

**Comment by Sixsoul** [comment]
Ah, apologies, corrected my CommandPanels version in the original post. Also, yeah, using pufferfish right now, my mistake, have been flipping between this and Paper frequently while troubleshooting issues for developers. Pufferfish only has slight changes to entity handling though, shouldn't influence this at all afaik.

Here is the full panel that is causing the issue:
```
panels:
  leaderboards_mid:
    perm: default
    rows: 3
    title: Example
    item:
      '1':
        material: "cps= self"
        name: "%cp-player-name%"
      '4':
        material: "cps= self"
        name: "%cp-player-name%"
      '7':
        material: "cps= self"
        name: "%cp-player-name%"
      '26':
        material: PAPER
        customdata: 10384
        name: ' '
  leaderboards_bot:
    perm: default
    rows: 1
    title: Example
    item:
      '0':
        material: PAPER
        customdata: 10384
        name: ' '
  leaderboards:
    perm: default
    rows: 6
    title: ':offset_-8:&f'
    item:
      '10':
        material: "cps= %ajlb_lb_servervariables_value_score_1_daily_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
        lore:
        - "&e► #1 • %ajlb_lb_servervariables_value_score_1_daily_name% • %ajlb_lb_servervariables_value_score_1_daily_value%"
        - "&8#2 - %ajlb_lb_servervariables_value_score_2_daily_name% - %ajlb_lb_servervariables_value_score_2_daily_value%"
        - "&8#3 - %ajlb_lb_servervariables_value_score_3_daily_name% - %ajlb_lb_servervariables_value_score_3_daily_value%"
      '19':
        material: "cps= %ajlb_lb_servervariables_value_score_2_daily_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
        lore:
        - "&8#1 • %ajlb_lb_servervariables_value_score_1_daily_name% • %ajlb_lb_servervariables_value_score_1_daily_value%"
        - "&e► #2 - %ajlb_lb_servervariables_value_score_2_daily_name% - %ajlb_lb_servervariables_value_score_2_daily_value%"
        - "&8#3 - %ajlb_lb_servervariables_value_score_3_daily_name% - %ajlb_lb_servervariables_value_score_3_daily_value%"
      '28':
        material: "cps= %ajlb_lb_servervariables_value_score_3_daily_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '37':
        material: "cps= %ajlb_lb_servervariables_value_score_4_daily_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '46':
        material: "cps= %ajlb_lb_servervariables_value_score_5_daily_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      #####
      '13':
        material: "cps= %ajlb_lb_servervariables_value_score_1_alltime_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '22':
        material: "cps= %ajlb_lb_servervariables_value_score_2_alltime_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '31':
        material: "cps= %ajlb_lb_servervariables_value_score_3_alltime_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '40':
        material: "cps= %ajlb_lb_servervariables_value_score_4_alltime_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '49':
        material: "cps= %ajlb_lb_servervariables_value_score_5_alltime_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      #####
      '16':
        material: "cps= %ajlb_lb_servervariables_value_score_1_weekly_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '25':
        material: "cps= %ajlb_lb_servervariables_value_score_2_weekly_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '34':
        material: "cps= %ajlb_lb_servervariables_value_score_3_weekly_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '43':
        material: "cps= %ajlb_lb_servervariables_value_score_4_weekly_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '52':
        material: "cps= %ajlb_lb_servervariables_value_score_5_weekly_name%"
        name: "&7ʀᴀɴᴋ • ɴᴀᴍᴇ • ѕᴄᴏʀᴇ"
      '53':
        material: PAPER
        customdata: 10384
        name: ' '
    commands-on-open:
    - open= leaderboards_mid {Middle}
    - open= leaderboards_bot {Bottom}
```
