### ISSUE TITLE
Web UI is not generating "OR" correctly

### ISSUE THREAD

**Issue by ryanalexmartin** [rockyhawk64/CommandPanels#273]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### What happened?

Using the "OR" logic sections generates the following YAML:

```
      '2':
        material: red_dye
        name: '&c設置Home r'
        commands:
          - sethome r
        lore:
          - '&7&l(Set home r)'
        has0:
          value0: r
          compare0: '%essentials_home_1%'
          value1: r
          compare1: '%essentials_home_2%'
          value2: r
          compare2: '%essentials_home_3%'
          value3: r
          compare3: '%essentials_home_4%'
          material: black_stained_glass_panel
```

However, I had to manually change the YAML into the following for the functionality to work:

```
      '2':
        material: red_dye
        name: '&c設置Home r'
        commands:
          - sethome r
        lore:
          - '&7&l(Set home r)'
        has0:
          value0: '%essentials_home_1% OR %essentials_home_2% OR %essentials_home_3% OR %essentials_home_4%'
          compare0: r
          material: black_stained_glass_pane
          name: 'Home has been set'
```

Great plugin, by the way!  

### Steps to reproduce the issue

Use the "OR" logical operators on the web UI.

### Expected behavior

The YAML should be generated with correct, functional "OR" logical operators to compare strings

**Comment by jman13378** [comment]
How exactly are you doing it in the UI (post a screenshot)

**Comment by ryanalexmartin** [comment]
![image](https://github.com/rockyhawk64/CommandPanels/assets/15975303/abdc735a-af4a-4e52-a483-92e028eceae2)

I used the OR logical operator, as seen in the screenshot, but the output YAML was malformed.

It should generate a single line with multiple OR logical operators, like so:
```
has0:
          value0: '%essentials_home_1% OR %essentials_home_2% OR %essentials_home_3% OR %essentials_home_4%'
          compare0: r
          material: black_stained_glass_pane
          name: 'Home has been set'
```

Instead, it gives multiple "value" blocks, (value0, value1, . . .) on multiple lines, which does not work in-game:
```
          value0: r
          compare0: '%essentials_home_1%'
          value1: r
          compare1: '%essentials_home_2%'
          value2: r
          compare2: '%essentials_home_3%'
          value3: r
          compare3: '%essentials_home_4%'
          material: black_stained_glass_panel      
```

Is the web editor open-source?  If so, I could take a look at it and try to make a pull request.
