### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kokqi** [rockyhawk64/CommandPanels#281]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [ ] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

**Suggestions**
- prevent the command (/<command>) from executing if doesn't specify <target> | **if target %chosenplayer% is stated in the panel.** e.g. /commandpanel <command> <target>
- remove %cp-search% backspace | like "daw**g**" remove the **g** on click tag
- regex support? to prevent click tags/general tags from performing if doesn't match

### Describe alternatives you've considered

.

### Screenshots/Videos (you can drag and drop files or paste links)

.

**Comment by kokqi** [comment]
![Uploading Screenshot_2023-12-18-19-39-38-039-edit_com.discord.jpg…]()

**Comment by kokqi** [comment]
suggestions unclear check discord instead 

https://discord.com/channels/602338405883314206/749407995036696656/1185437702280187945

**Comment by rockyhawk64** [comment]
Commands currently have now been set so they will only open the panel if the correct amount of arguments have been provided, eg:
```YAML
panels:
  template:
    perm: default
    rows: '6'
    title: '&4Template GUI'
    commands:
    - template %test1%
    item:
      '2':
        material: STONE
        name: '%cp-test1%'
```
/template <-- will not work
/template hello <-- will work
/template hello extra <-- will not work
