### ISSUE TITLE
Duplicate Items with actions

### ISSUE THREAD

**Issue by FrancescoJacovo** [rockyhawk64/CommandPanels#282]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

I'm always frustrated when i want to create textured GUIs but if i want to add commands on multiple slots i have to create one item for every slots.

### Describe the solution you'd like

Copy the actions also on "duplicated-items"

### Describe alternatives you've considered

Nothing more, it's like a multi-slot features of other classic plugins. I think that with this will be really complete.

**Comment by FrancescoJacovo** [comment]
Bump

**Comment by FrancescoJacovo** [comment]
Bump

**Comment by rockyhawk64** [comment]
To do this you should be using anchors to duplicate commands between items like this:

```YAML
panels:
  template:
    perm: default
    rows: '6'
    title: 'Template Panel'
    item:
      '1': 
        material: DIAMOND
        name: click me
        commands: &item_1_commands
        - heal
        - cpc
        - msg= you have been healed
      '2': 
        material: IRON_INGOT
        name: click me
        commands: *item_1_commands
      '3': 
        material: COAL
        name: click me
        commands: *item_1_commands
```

**Comment by FrancescoJacovo** [comment]
I want to create big buttons for GUI with texture. Is there a way to create a single item with all metas information and commands rather than create eighteen differents entries?

**Comment by rockyhawk64** [comment]
You would have to do the same thing but duplicate the item instead of just the commands:
```YAML
panels:
  template:
    perm: default
    rows: '6'
    title: 'Template Panel'
    item:
      '1': &item1
        material: DIAMOND
        name: click me
        commands:
        - heal
        - cpc
        - msg= you have been healed
      '2': *item1
      '3': *item1
```
