### ISSUE TITLE
Left/Rightclick doesnt work

### ISSUE THREAD

**Issue by Cybrie** [rockyhawk64/CommandPanels#31]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Describe the Issue
So i have a hardcore server and I wanted to do it in such a way that you can buy additional life through the panel, which also works.
The only problem is that it only works when I open the panel.
If I set that you have to left / right click, it no longer works.
And every command I move with left/right= no longer works

### Expected behavior
/
### Screenshots/videos
/

### Versions:
 - Minecraft: [e.g. 1.16.1]
 - CommandPanels: [e.g. 3.5.1]

### Additional context/Panel files
https://pastebin.com/nEMLEAWc
this is an e.g.

**Comment by fireFerry** [comment]
Hello! Your commands section wasn't lined up correctly. Yours was this:
```yaml
panels:
  panel-1:
    perm: default
    rows: 3
    title: Lifes
    command: lifes
    empty: BLACK_STAINED_GLASS_PANE
    item:
      '13':
        material: REDSTONE_BLOCK
        name: ''
    commands:
    - right= buycommand= 10 heal %cp-player-name%
```
But it needs to be like this:
```yaml
panels:
  panel-1:
    perm: default
    rows: 3
    title: 'Lifes'
    command: punish
    empty: BLACK_STAINED_GLASS_PANE
    item:
      '13':
        material: REDSTONE_BLOCK
        name: ''
        commands:
        - right= bucommand= 10 heal %cp-player-name%
```
