### ISSUE TITLE
PLEASE HELP ME

### ISSUE THREAD

**Issue by MeoNguOfficial** [rockyhawk64/CommandPanels#330]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your issue is a duplicate and your problem already has been solved?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### What server version are you running?

1.2

### What CommandPanels version are you using?

latest

### What server software are you running?

Purpur

### Describe the Issue

I need ssomeone help me! i want to create a menu rank using PlayerPoints plugin

### Expected behavior

I dk how to make a menu rank panel on this plugin using PlayerPoints

### Additional context/Panel files

nothing

**Comment by rockyhawk64** [comment]
This is an example of a rankup menu that uses luckperms:
```YAML
panels:
  tinyrankup:
    perm: default
    rows: 3
    title: '&8&l-----( &5&lTiny Rankup &8&l)-----'
    sound-on-open: BLOCK_NOTE_BLOCK_CHIME
    commands:
      - ranks
      - rank
      - rankup
      - premote
    empty: PURPLE_STAINED_GLASS_PANE
    item:
      '9':
        material: DIRT
        name: '&eDirt'
        lore:
          - '&eDefault Rank'
          - '&7No Perks'
        has0:
          value0: '%cp-player-name% HASPERM'
          compare0: rank.dirt
          material: DIRT
          name: '&e&lDirt'
          enchanted: true
          lore:
            - '&a&lOwned'
            - '&7No Perks'
          has0:
            value0: '%cp-player-name% HASPERM'
            compare0: rank.cobble
            material: DIRT
            name: '&e&lDirt'
            lore:
              - '&c&lOwn Higher Rank'
              - '&7No Perks'
        has1:
          value0: NOT %cp-player-name% HASPERM
          compare0: rank.dirt
          material: DIRT
          name: '&e&lDirt'
          lore:
            - '&e&lPurchase! $1000'
            - '&7No Perks'
          commands:
            - paywall= 1000
            - console= lp user %cp-player-name% parent set default
      '11':
        material: COBBLESTONE
        name: '&7Cobblestone'
        lore:
          - '&eCobble Rank'
          - '&7/Feed'
        has0:
          value0: '%cp-player-name% HASPERM'
          compare0: rank.cobble
          material: COBBLESTONE
          name: '&7&lCobblestone'
          enchanted: true
          lore:
            - '&a&lOwned'
            - '&7/Feed'
          has0:
            value0: '%cp-player-name% HASPERM'
            compare0: rank.iron
            material: COBBLESTONE
            name: '&7&lCobblestone'
            lore:
              - '&c&lOwn Higher Rank'
              - '&7/Feed'
        has1:
          value0: NOT %cp-player-name% HASPERM
          compare0: rank.cobble
          material: COBBLESTONE
          name: '&7&lCobblestone'
          lore:
            - '&e&lPurchase! $1000'
            - '&7/Feed'
          commands:
            - paywall= 1000
            - console= lp user %cp-player-name% parent set cobble
          has0:
            value0: NOT %cp-player-name% HASPERM
            compare0: rank.dirt
            material: COBBLESTONE
            name: '&7&lCobblestone'
            lore:
              - '&4&lNeed Previous Rank'
              - '&7/Feed'
      '13':
        material: RAW_IRON
        name: '&fIron'
        lore:
          - '&eIron Rank'
          - '&7/Feed'
          - '&7/Craft'
        has0:
          value0: '%cp-player-name% HASPERM'
          compare0: rank.iron
          material: RAW_IRON
          name: '&f&lIron'
          enchanted: true
          lore:
            - '&a&lOwned'
            - '&7/Feed'
            - '&7/Craft'
          has0:
            value0: '%cp-player-name% HASPERM'
            compare0: rank.diamond
            material: RAW_IRON
            name: '&f&lIron'
            lore:
              - '&c&lOwn Higher Rank'
              - '&7/Feed'
              - '&7/Craft'
        has1:
          value0: NOT %cp-player-name% HASPERM
          compare0: rank.iron
          material: RAW_IRON
          name: '&f&lIron'
          lore:
            - '&e&lPurchase! $2500'
            - '&7/Feed'
            - '&7/Craft'
          commands:
            - paywall= 2500
            - console= lp user %cp-player-name% parent set iron
          has0:
            value0: NOT %cp-player-name% HASPERM
            compare0: rank.cobble
            material: RAW_IRON
            name: '&f&lIron'
            lore:
              - '&4&lNeed Previous Rank'
              - '&7/Feed'
              - '&7/Craft'
      '15':
        material: DIAMOND
        name: '&bDiamond'
        lore:
          - '&eDiamond Rank'
          - '&7/Feed'
        has0:
          value0: '%cp-player-name% HASPERM'
          compare0: rank.diamond
          material: DIAMOND
          name: '&b&lDiamond'
          enchanted: true
          lore:
            - '&a&lOwned'
            - '&7/Feed'
            - '&7/Craft'
            - '&7/Stonecutter'
          has0:
            value0: '%cp-player-name% HASPERM'
            compare0: rank.netherite
            material: DIAMOND
            name: '&b&lDiamond'
            lore:
              - '&c&lOwn Higher Rank'
              - '&7/Feed'
              - '&7/Craft'
              - '&7/Stonecutter'
        has1:
          value0: NOT %cp-player-name% HASPERM
          compare0: rank.diamond
          material: DIAMOND
          name: '&b&lDiamond'
          lore:
            - '&e&lPurchase! $5000'
            - '&7/Feed'
            - '&7/Craft'
            - '&7/Stonecutter'
          commands:
            - paywall= 5000
            - console= lp user %cp-player-name% parent set diamond
          has0:
            value0: NOT %cp-player-name% HASPERM
            compare0: rank.iron
            material: DIAMOND
            name: '&b&lDiamond'
            lore:
              - '&4&lNeed Previous Rank'
              - '&7/Feed'
              - '&7/Craft'
              - '&7/Stonecutter'
      '17':
        material: NETHERITE_INGOT
        name: '&8Netherite'
        lore:
          - '&eNetherite Rank'
          - '&7/Feed'
        has0:
          value0: '%cp-player-name% HASPERM'
          compare0: rank.netherite
          material: NETHERITE_INGOT
          name: '&8&lNetherite'
          enchanted: true
          lore:
            - '&a&lOwned'
            - '&7/Feed'
            - '&7/Craft'
            - '&7/Stonecutter'
            - '&7/Enderchest'
        has1:
          value0: NOT %cp-player-name% HASPERM
          compare0: rank.netherite
          material: NETHERITE_INGOT
          name: '&8&lNetherite'
          lore:
            - '&e&lPurchase! $10,000'
            - '&7/Feed'
            - '&7/Craft'
            - '&7/Stonecutter'
            - '&7/Enderchest'
          commands:
            - paywall= 10000
            - console= lp user %cp-player-name% parent set netherite
          has0:
            value0: NOT %cp-player-name% HASPERM
            compare0: rank.diamond
            material: NETHERITE_INGOT
            name: '&8&lNetherite'
            lore:
              - '&4&lNeed Previous Rank'
              - '&7/Feed'
              - '&7/Craft'
              - '&7/Stonecutter'
              - '&7/Enderchest'

```
If you want to make one instead using PlayerPoints you can use the PlaceholderAPI placeholders here to know how many points players have in the panel:
```
%playerpoints_points%
%playerpoints_points_formatted%
%playerpoints_points_shorthand%
```
https://wiki.placeholderapi.com/users/placeholder-list/#playerpoints
