### ISSUE TITLE
implement input-cancel-comamnds

### ISSUE THREAD

**Issue by derpykid300** [rockyhawk64/CommandPanels#345]
### Terms

- [x] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [x] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [x] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

No

**Implement a feature to send commands to the player when on cancelling player-input:**

input:
  input-cancel: cancel
  input-cancelled: '&cCancelled!'
  max-input-length: -1
  input-message: []

EXPECTATION:

```
  input-cancel-commands:
  - msg= $<title:0:0t:0:""> 
  - rtp
  - examplecommand2
```

### Describe the solution you'd like

None

### Describe alternatives you've considered

No

**Comment by TinyTank800** [comment]
I believe i have got a working version of this. You can try this dev build attached. Formatting for this new addition is like this:

```YAML
panels:
  panel-1:
    perm: default
    rows: 3
    title: '&8Generated panel-1'
    empty: BLACK_STAINED_GLASS_PANE
    item:
      '12':
        material: DIAMOND_SWORD
        stack: 11
        player-canceled-input:
        - "console= say wow cant beleive you."
        - console= give %cp-player-name% diamond 1
        player-input:
        - "console= say hi %cp-player-input%"
        commands:
        - "msg= hello world"
        - cpc
```

[CommandPanels-DEV.zip](https://github.com/user-attachments/files/18933214/CommandPanels-DEV.zip)
