### ISSUE TITLE
Strange, inconsistent behavior with cursor resetting on GUI opening

### ISSUE THREAD

**Issue by CoolLord22** [rockyhawk64/CommandPanels#347]
### Terms

- [x] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
- [x] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your issue is a duplicate and your problem already has been solved?
- [x] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### What server version are you running?

1.2

### What CommandPanels version are you using?

latest

### What server software are you running?

PaperMC

### Describe the Issue

Copy pasting relevant context/messages from the Discord...

CoolLord22
> Hello! I've got a complex UI system where another plugin's GUI issues a command to open up a CommandPanels GUI, however we're having a slight issue with the player's mouse cursor returning to the center of the screen when CP panel is opened from a non-CP context.
We've already got it sorted using open= when opening different CP panels from other CP panels, however in the context where console issues /cp <panel> <player> the cursor still returns to center. 

[ENG] TinyTank800
> Since its going from one plugin to another it's "opening a new container" when you swap uis. This is what causes the centering i think. Unsure on how to fix as they are separate plugins.

CoolLord22
> I thought this was the case... But i'm a bit more confused as to what specifically is triggering this cursor resetting. I'll elaborate in more details below...
Here is what I have set up
- **Hub panel** which has CP item click to open **UltraCosmetics menu**, using `uc menu` as player command
- **UC menu** has item click to return player to **hub panel**, using `sudo %player% cp hubpanel`
- **UC menu** has item click to open a custom cosmetic CP panel **appearance**, using `sudo %player% cp appearancepanel`
- **appearance panel** has item click to return player to  **UltraCosmetics menu**, using `uc menu` as player command

> This resetting of cursor interestingly only happens on the UC menu > appearance panel... Opening hub from UC, opening UC from hub, don't trigger cursor resets, only the UC to appearance panel does... 
Are there any panel specific configs / config settings in general that could be altering this behavior for one panel and not another?

### Expected behavior

The resetting behavior of the cursor should be consistent, either it goes to center of screen EVERYTIME or NONE of the times. The way my panels are set up is identical, but having one behavior when returning to one panel but the opposite on the other feels inconsistent and messy. Was wondering if I need to change something on my end, or if this is an issue within CP...

### Additional context/Panel files

Server version for terms doesn't show 1.21.4, but providing more version details below
```
[15:43:13 INFO]: This server is running Paper version 1.21.4-187-main@1d5e5a5 (2025-02-28T19:53:30Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
ver CommandPanels
[15:43:15 INFO]: CommandPanels version 3.21.5
[15:43:15 INFO]: Fully Custom GUIs. Make your Server Professional.
[15:43:15 INFO]: Author: RockyHawk
```

### Screenshots/Videos (you can drag and drop files or paste links)

Video showcasing the inconsistent cursor behavior:
https://github.com/user-attachments/assets/e39664a3-9002-4eba-8d99-1b23245876bf

```yaml
panels:
  customizeappearance:
    perm: default
    rows: 6
    title: Customize Appearance
    empty: AIR
    item:
... not sure if item configs are necessary?
```
```yaml
panels:
  mythrendservers:
    perm: default
    rows: 6
    title: Mythrend Network
    empty: AIR
    open-with-item:
      material: COMPASS
      name: '&6Server Menu &e(Right-Click)'
      lore:
      - '&8Choose what you want to play!'
      stationary: 4
    item:
... not sure if item configs are necessary?
```
