### ISSUE TITLE
Open requirements

### ISSUE THREAD

**Issue by TinyTank800** [rockyhawk64/CommandPanels#363]
### Terms

- [x] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [x] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [x] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

An open requirements section for panels so people need specific conditions before the panel even opens.

Has section formatting?
```
can-open: false
has0:
  value0: '%name'
  compare0: 'rockyhawk'
  can-open: true
```

### Describe the solution you'd like

Has section formatting?
```
can-open: false
has0:
  value0: '%name'
  compare0: 'rockyhawk'
  can-open: true
```

### Describe alternatives you've considered

.
