### ISSUE TITLE
Too frequent placeholder checks causing huge lags

### ISSUE THREAD

**Issue by DeadByDays** [rockyhawk64/CommandPanels#366]
### Terms

- [x] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [x] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [x] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [x] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.2

### What CommandPanels version are you using?

latest

### What server software are you running?

Other

### What happened?

I purchased a server setup from BBB a long time ago and discovered a bug that, as it turns out, is most likely related to CommandPanels.

As far as I understand, the issue is connected to the update frequency of placeholders for certain menus. The problem is very evident: if 2-3 players open these menus simultaneously, a huge server TPS drop occurs.

The placeholders themselves are created using skript-placeholders.jar. Other Skript-related plugins in use are skript-reflect.jar, skript-yaml.jar, SkBee and Skript.jar.

Is it possible to reduce the update frequency of these placeholders? For example, through CommandPanels settings, by adjusting the Skripts, or via some other method to improve performance? 

### Steps to reproduce the issue

https://builtbybit.com/resources/unlimited-adventures-survival-setup.27917

### Expected behavior

?

### Error (optional)

```shell

```

### Screenshots/Videos (you can drag and drop files or paste links)

https://cdn.discordapp.com/attachments/1346407406929707079/1346407410151194625/Minecraft_2025.03.04_-_11.59.50.02.mp4?ex=682c451d&is=682af39d&hm=abf7657baa262655f3a1b40100b88dfff5e748a124275cc18d243dd39835e7c8&

**Comment by rockyhawk64** [comment]
How frequently the placeholders are updates depends on your CommandPanels settings rather than there being a bug. If you open a Panel but make it static it will just run the placeholder once. If you want to globally stop refreshes you can set `refresh-panels` to false in the config.yml. Otherwise, you can add the static panel type to your panels and that will stop refreshing for those panels specifically
eg for panel specific option:
```YAML
panels:
    template:
        perm: admin
        rows: '6'
        title: '&8New Panel'
        empty: AIR
        panelType: #<--- adding static panel type
        - static
        item:
            '4':
                material: COBBLESTONE
                stack: 1
                name: '&fClick Me!'
                commands:
                - msg= You clicked, the item!
                - cpc
```
