### ISSUE TITLE
Toggle not working

### ISSUE THREAD

**Issue by GunnerBasil** [rockyhawk64/CommandPanels#4]
**Describe the bug**
The item meant to toggle the game mode doesn't toggle.

**To Reproduce**
1. Add a panel with the following code:
```
panels:
  panel-1:
    perm: default
    rows: 3
    open-with-item:
      material: NETHER_STAR
      ID: '0'
      name: '&aSettings'
      lore:
      - '&2Change gamemodes, toggle anticheats, etc.'
      stationary: '8' #this will force the item to stay in the inventory hotbar in a certain location (0-8)
    title: 'Settings'
    command: panel-1
    empty: STAINED_GLASS_PANE
    emptyID: '15'
    item:
      '12':
        material: REDSTONE_TORCH_ON
        name: Anticheats
      '14':
        material: DIAMOND_BLOCK
        name: Current game mode - &aCreative
        lore:
        - 'Click to switch to Survival'
        commands:
        - console= pex user %cp-player-name% add commandpanel.toggle.gamemodesurv.on
        - gamemode survival
        hasperm:
          perm: commandpanel.toggle.gamemodesurv.on
          material: DIRT
          lore:
          - 'Click to switch to Creative'
          commands:
          - console= pex user %cp-player-name% remove commandpanel.toggle.gamemodesurv.on
          - gamemode creative
          name: 'Current game mode - &aSurvival'
      '22':
        material: WOODEN_DOOR
        name: Exit
        commands:
        - cpc
```
2. try opening the panel and clicking the toggle game mode button.

**Expected behavior**

**Screenshots**

**Versions:**
 - Minecraft: 1.12.2
 - CommandPanels: v2.10.0-classic

**Additional context**
Server: PaperMC 1.12.2
