### ISSUE TITLE
[Need Help] Can't find the error / Bug found

### ISSUE THREAD

**Issue by Endphoenix** [rockyhawk64/CommandPanels#42]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if the solution for your problem is there?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your issue is a duplicate and your problem already has been solved?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes, I was allowed to report my problem directly here without anyone in the Discord having looked at it closely.

### Describe the Issue
A clear and concise description of what the problem is.

I think I found another bug or I made a mistake:

I've written an Enchant-Upgrade-GUI, to upgrade the limit of enchantments a player can have. The Permission (ae.limit.<limit>), which I used is from another Plugin.

I did it all like this: There are 7 levels in total. The cost per level increases with each level. I have shown the levels like this:

- Level 1 - Brick
- Level 2- Coal
- Level 3 - Iron Ingot
- Level 4 - Gold Ingot
- Level 5 - Diamond
- Level 6 Emerald
- Level 7 - Nether Star

You only ever see as many levels up to the level you have unlocked. The rest is grey dye. Also, the latest level (the place you are) is enchanted.

You can take a closer look at the whole thing in the Panel File.

If I upgrade everything to Emerald, It has the lore: 

- '&7You can have &e25 Enchantments &7per Item.'
- '&aUnlocked'

When I buy the emerald, I unlock the Nether Star (Level 7), and it has the right lore, but it isn't enchanted.

If I buy the Nether Star, it is enchanted, but it has the lore:

- '&7You can have &e25 Enchantments &7per Item.'
- '&7Price: &a75.000 coins'
- '&cLocked'

I don't know I'm doing wrong :pensive: . Can you help me please, or is it another bug?

### Expected behavior

You look at the whole thing and say if I have a mistake. If you don't find one you test the whole thing yourself and see if that's a bug or not. If this is a bug then you try to fix it. If you can't find a bug, ask me more questions.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.

### Versions:
 - Minecraft: 1.14.4 
 - CommandPanels: 3.7.4

### Additional context/Panel files
Add any other context about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.

https://pastebin.com/QNrzgStr

**Comment by rockyhawk64** [comment]
It looks like an indentation issue with the last enchanted part.
You had this:
```YAML
hasperm:
  output: true
  perm: commandpanel.enchantment.level7
  material: NETHER_STAR
  name: '&7Level &e7'
  lore:
  - '&7You can have &e30 Enchantments &7per Item.'
  - '&aUnlocked'
enchanted: true
```
But I think you wanted to do this:
```YAML
hasperm:
  output: true
  perm: commandpanel.enchantment.level7
  material: NETHER_STAR
  name: '&7Level &e7'
  lore:
  - '&7You can have &e30 Enchantments &7per Item.'
  - '&aUnlocked'
  enchanted: true
```
