### ISSUE TITLE
Suggestion: Temporary/One-Time-use Panels

### ISSUE THREAD

**Issue by leasoncre** [rockyhawk64/CommandPanels#50]
####port from discord, old suggestion that was lost somewhere along the line####
```yml
###Origionally written on 6/5/2020###
#=================================#
#idea/explanation:
#=================================#
#Method to impliment ad-hoc/ temporary/ generated panels 
#(in support of CP effectively being able to replace any panel-based plugin. at least for potentially replacing shop plugin(s))

#=================================#
#=========== config.yml ==========#
#=================================#
#for larger serververs the creation/deletion of panels may become process-intensive. if the task is ASYNC that shouldn't be an issue, if this is not possible (ie: not Paper server), then the only thing you can do to mitigate some of that process might be to add a delay somewhere. though i'm not sure where since the creation is needed immediately.
#adding a purge delay, could be useful if a user goes back to that menu often/before it is deleted. (if set to something like 5min a player wouldn't need to regenerate the panel every time they open it. timer starts on panel close/player-disconnect(unexpected)
#if a panel is specifed as ad-hoc-persist, then it will generate the first time it is called for, but not be purged and regenerated the next time it is called. it is also not player-specific-only-access
#both [ad-hoc], and [ad-hoc-persist] are needed to facilite different methods/designs of shops:
  #[ad-hoc] are player-specific and non-persistant. Only that player can see the panel. Great for a buy screen that is self-updating (add-qty/remove-qty before buying - prevents other users from accessing that user's buy panel at the same time)
  #[ad-hoc-persist] is great because panels are only generated once as-needed, and the panel won't need any variable updates later (all available qty's listed on 'one panel'

#time in miliseconds(or ticks?). 1000=1Second, 60000=1min, 300000=5min
ad-hoc-destroy-delay: 30000

#time in minutes before a persistant panel is considered 'stale'/not needed anymore (good for freeing up memory from panels infrequently opened)
#'-1' = disabled, '0' = immediately(why are you not using non-persistant ad-hoc panel setting!?!?), 
#recomended setting if needed: less than 30 active players: couple hours?. 30-50 active players: 30min?. 50+ active players: 5min or less?.
ad-hoc-persist-destroy-delay: -1

#should we cache the active ad-hoc panels in memory to disk when the /restart or /stop command is run? (Does not persist if server crashes. file is erased on successful load.)
#this is not reccomended, loading several thousand panels on startup can considerably lag the server core processing thread if it is not ASYNC (Get Paper!)
ad-hoc-persist-on-restart: false

#should CP operate in ASYNC mode? (Note: Only works with Paper! Bukkit and Spigot cannot do this)
async-processing: true

#=================================#
#========= Default panel =========#
#=================================#
panels:
  RegularPanel:
    paneltype: default
    perm: regularpanel
    rows: '6'
    title: 'Regualr Panel'
    command: RegularPanel
    empty: AIR
    items:
      '1':
        material: beacon
        name: '&e&lBuy a Beacon!'
        #How to define variables:
        variables:
          #syntax expectation example:
          #'<var_namespaced_string>': '<variable value string>'
          #variable defined within this item (references the above [material: <value>] set to this item
          #NOTE: variables CANNOT be the same name as existing panel fields! (ex: you cannot use 'name' or 'material' as a variable) - this might cause a lookup loop within the ad-hoc item.
          # '$<var>$' format used to represent internal variables in format similar to PAPI, if PAPI can be used internally instead, Heck yeah! (maybe: %cp_<var>% (Variable NOT referenceable outside of CP)
          #variable names are NOT case-senseative. (just easier to read)
          #PAPI-style formating may be needed to support %MATH_<math_functions>% operations which is highly likely for a servershop style GUI
          #if using PAPI internally is possible i'd think all referenced names would need an internal prefix of something like 'cpi_' (CommandPanelsInternal) when referenced by an external PAPI parsing function
          'mat2': $material$
          #staticly defined variable:
          'pname2': '&e&lBeacon Purchase Panel'
          'price2': 1000
          'name2': 'Beacon' #('Friendly' name)
          #([perm] can have a number after it for certain use-cases, example substituted with letter :p)
          'permB': beacon #(or catagory of item)
        commands:
        #specify variables in (CSV? format) to pass to the next panel opened with the command: (if a variable is defined within the item, but not specifed here, it does nothing It is possible to send the same variable multiple times. (ex: var= price,pname,price,mat) should you want to
        #----??? (pass both the variable name and value? or just value?)
        - left= var= mat2,pname2,price2,name2,permB cp Ad-Hoc-PersistPanel


#-----------------------------
#built-in variables: (CANNOT be redefined (left side of ['<var>': '<value>']))
  #all panel settings have a 'p' in front of them. ie: ptitle = 'Regualr Panel' in the example above (this is to avoid duplicate variables, such as [perm:])
  #all item settings are the same as thier existing name. ie:(item:'1' above) name = '&e&lBuy a Beacon!'
  #all items with list values (like lore: and commands:) are automatically predefined as [lore<line#>] ex: lore1,lore2 for each line number respectively.
  #'null' can be used to pass a '0' value if that position in the CSV is not needed for w/e reason???? (was thinking more complexly defined default panel items, but that's just jumping down a rabit hole... i like rabit holes :p) - hasvalue function could be used to alter panels with variables... oooooOOOO... how can i use that.... >_>

#----Note: if a builtin variable is NOT referenced in the [var= <list>], DO NOT PARSE/CREATE IT (waste of processing). [@end of file/panel read, if var not used, purge for that panel] #memory management
#-----NOTE: if using PAPI to parse internal variables, those variables would need to be defined BEFORE they are passed to PAPI for parsing. (esp numbers stored/read as strings... nightmare)


#=================================#
#===== Ad-Hoc-Persist Panel ======#
#Generated on-the-fly and persists in memory until a maintenance/purge cycle is run (automatically or via command) or the server is restarted.
#=================================#
  #baseline reference for generated panel(s)
  Ad-Hoc-PersistPanel: #<----does this matter? if it needs to be defined during ad-hoc creation, i would just use the same name as the command. if it does the FIRST value passed through with the var=<CSV> would need to be that string.
    paneltype: ad-hoc-persist
    #----(If passing only the values from the previous panel:
    #re-define the variable names, IN ORDER that they were specified from the previous panel: (ie: the first variable you define here will contain the first value in the CSV list)
    #if you are using ANY variables in the panel itsel, they MUST be defined BEFORE they can be used in the intended field(s). (ie: define them before any other panel setting)
    #optional field if type: default
    define-variables:
    # (The : <value> is defined by the CSV order, so there is no need to use an array format)
    - 'Ad-mat2'
    - 'Ad-pname2'
    - 'Ad-price2'
    - 'Ad-name2'
    - 'Ad-permB'
    #----(If passing both the variable name AND value: the names and values are stored in memory and purged after the panel has been generated. (the redefined variables listed above would not be needed.)
    #using a variable for a perm node: in this example would end up with: [commandpanels.panel.beacon]
    perm: $Ad-permB$
    #using a variable to define aditional characters in a permission node: (This is not needed for panels that do not persist) in this example would end up with: [commandpanels.panel.buybeacon]
    perm0: buy$Ad-permB$ #'perm0' current WIP at time of writing
    rows: '6'
    #setting the panel title with a variable:
    title: $Ad-pname2$
    command: buy$Ad-permB$
    empty: AIR
    items:
      '1': #yes, sigh.... even this could be defined by a variable..., though NOT reccomended.
        material: $Ad-mat2$
        name: '&e&lBuy 1x $Ad-name2$!'
        #again, you can define variables to be passed to the next panel. (not used in this example)
        variables:
          'blah': 'blah'
        commands:
        - left= paywall= %MATH_ROUND({Ad-price2}*1,2)% console= give %cp-player-name% $Ad-mat2$ $Ad-price2$ 1

      '2':
        material: $Ad-mat2$
        name: '&e&lBuy 2x $Ad-name2$!'
        commands:
        - left= paywall= %MATH_ROUND({Ad-price2}*2,2)% console= give %cp-player-name% $Ad-mat2$ $Ad-price2$ 2

#=================================#
#========= Ad-Hoc Panel ==========#
#Generated on-the-fly and only exists for that player while they have it open. panel purged from memory afterwards.
#=================================#
  Ad-HocPanel:
    paneltype: ad-hoc
    define-variables:
    - 'Ad-mat2'
    - 'Ad-pname2'
    - 'Ad-price2'
    - 'Ad-name2'
    - 'Ad-permB'
    #variables local to the specific panel, not used outside of the panel. these are loaded when the panel is first opened by the specific player. The valuue of this can be manipulated only from within the panel and does not persist beyond the panel being closed. (not exclusive to ad-hoc panel type)
    local-variables:
      #initial value of player-and-panel-specific-variable:
      'qty': 1
    perm: $Ad-permB$
    perm0: buy$Ad-permB$ #'perm0' current WIP at time of writing
    rows: '6'
    title: $Ad-pname2$
    command: buy$Ad-permB$
    empty: AIR
    items:
      '1':
        #remove 1 from a variable value
        material: red_glass_pane
        name: '&c-1'
        commands:
        #new command needed to manipulate value:
        #syntax: cplocalvariable <EXPRESION-TYPE> <variable|number1> <operator1> <variable|number2> [(optional)operator2] [(optional)number3] [[etc......]] = <output_to_variable>
        #EXPRESION-TYPE: what operation is this? [MATH] (current default/(only option?) until more complex text-functions may be added [SEARCH|REPLACE|etc..] (i'm used to excel formulas and text manipulation there)
        #could PAPI MATH (EvalEx) be used here? https://github.com/uklimaschewski/EvalEx (that shit still confuses me, but looks rich in functions)
        #additionally/later-on: support text-based functions/manipulations, far more complicated, so not a 'priority' for this suggestion.
        - cplvar $qty$ - 1

      '2':
        #actually buy the item qty for price multiplied by qty.
        material: $Ad-mat2$
        name: '&e&lBuy $qty$x $Ad-name2$!'
        commands:
        - left= paywall= %MATH_ROUND({Ad-price2}*{QTY},2)% console= give %cp-player-name% $Ad-mat2$ $Ad-price2$ $qty$

      '3':
        #add 1 to a variable value
        material: lime_green_glass_pane
        name: '&a+1'
        commands:
        - cplvar $qty$ + 1 $qty$

#- - - - You(enduser) could optionally add a layer to this that would setup the same panel for stack buying as well(instead of opening another one). localvariabes: 'buytype': 'single' || 'stack' 'stackmultiplier': 1 || 64 -&&- hasvalue: $buytype$ && add the multiplier to the command MATH() to change the panel's look/item material w/o generating a new panel, it would just alter the existing panel. #fancy, but functional.

#=================================##=================================#
#=================================##=================================#
```

> #chat logs from patron-suggestions:
> Leasoncre04:53:24 PM, 05/10/2020
> Rocky, you're going to hate me or love me, or be confused about which one to stick with... >< o.O
> i have an idea all laied out for ya, just needs the dev side [link dead, this file replaces]
> RockyHawk05:58:32 PM, 05/10/2020
> ahh hmmmm
> I am still not sure what ad-hoc means but I think I understand what it does
> I like the "panelType" part, I can make one like async, animated, etc
> also the use of the variables, what do these do exactly? Could there be global variables outside of the items maybe and those ones could be used in any item
> (global as in anywhere in the one panel)
> Leasoncre02:54:15 PM, 05/12/2020
> `﻿ad-hoc﻿` wifi: create a wifi network on-the-fly. usu used to share internet connection.
> I'm not sure what the common term for 'on-the-fly'/temmporary is
> escape to cancel • enter to save
> the (ex)'pname' would be a global one, within the panel itself.
> Though, now i think of it. there might be call at some point for a global-variable /outside/ of a single panel (actual global)
> better idea:
> prefix names with 'g' for 'global', 'p' for 'panel', and 'i' for 'item'
> each specifies the variable reference level. (and allows for a generic 'name' variable to be used)
> ex: gcustomname would have to be defined in a main config somewhere on load (usecase: panel accessible only during certain times?)
> ptitle is the title of the panel
> iname would be the name of the item
> (referencing other panels/items not supported/needed?)
> Leasoncre04:23:39 PM, 05/12/2020
> panel type 'names' alternatives:
> persistant(aka: default)
> one-time-use([ad-hoc] per-player, expires when closed)
> temporary([ad-hoc-persist] any-player, timed expire)
```yml
#=================================#
#=========Item-transfer ==========#
#=================================#
#never finished this idea for a sell-type-screen. ideas might be too complex to impliment easily. I think 90% of it would be plugin-side...
###8/21/2020: Still to lazy to try and bash my head into this idea further (sell screen) - just use essentials /sellall command
```
