### ISSUE TITLE
Editing a group of same items

### ISSUE THREAD

**Issue by CroaBeast** [rockyhawk64/CommandPanels#64]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Is your feature request related to a problem? Please describe.
It's too frustrating edit ALL the custom items that ARE THE SAME.

### Describe the solution you'd like
Will be cool if some group of items, that are identical, will be edited in one section, like will be a one item.

### Describe alternatives you've considered
Mmm... I explained all that I need to say about that new feature.

### Additional context
Nothing to add.

**Comment by CroaBeast** [comment]
wait, that feature will be added? or it is not possible? .w.

**Comment by rockyhawk64** [comment]
Beta testing the feature currently, this is an example of how it will work next update (3.12.7) when it is released:
```YAML
      '11':
        material: RED_STAINED_GLASS_PANE
        duplicate: 3-7
        name: Duplicated Item
```
That will duplicate the item on slots 3 to 7
OR you can also do something like this:
```YAML
      '11':
        material: RED_STAINED_GLASS_PANE
        duplicate: 3-7,8-10,11,13
        name: Duplicated Item
```
That will duplicate the item to slots 3 to 7, slots 8 to 10, slots 11 and 13. The duplicated items will not override existing items, so they will only be placed in empty slots. They also will not duplicate commands. (visual only).
