### ISSUE TITLE
[Suggestion] Sell Custom Items

### ISSUE THREAD

**Issue by BlazenFury908** [rockyhawk64/CommandPanels#91]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
Yes/No
Yes

### Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes/No
Yes

### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes/No
Yes

### Is your feature request related to a problem? Please describe.
No, not really.

### Describe the solution you'd like
I would like to be able to sell custom items (ex. Crackshot Weapons, Vouchers, Renamed Items, etc.

### Describe alternatives you've considered
I have considered getting a different plugin, but none are as good as this one.

### Additional context

Edit:
I forgot to mention that this could be done through the menu, but I am not a dev so I have no idea how hard that would be.

**Comment by fireFerry** [comment]
Hello! You didn't ask this is the Discord server, and if you looked closely at the wiki, you can see this is already available.
![image](https://user-images.githubusercontent.com/61279925/103269830-e7658e00-49b6-11eb-8fd3-e0b7b1b270ae.png)
![image](https://user-images.githubusercontent.com/61279925/103269847-f2202300-49b6-11eb-9818-02ab02b98a3c.png)

**Comment by rockyhawk64** [comment]
Ensure you have the latest update using `/cpv`.
I have also made a panel that only works on the latest version, but is an easy example of how to do this.
```YAML
panels:
  customitem:
    perm: default
    rows: 1
    title: 'Custom Panel'
    empty: GLASS_PANE
    custom-item:
      item1:
        material: STONE_SWORD
        name: "&c&lGods Sword"
        lore:
        - "&4Has special abilities!"
        - "&f- Lightning (5s delay)"
        - ""
        - "&7Click to get item"
    item:
      '2':
        material: STONE_SWORD
        name: "&c&lGods Sword"
        lore:
        - "&4Has special abilities!"
        - "&f- Lightning (5s delay)"
        - ""
        - "&7Click to get item"
        commands:
        - give-item= item1
      '6':
        material: FURNACE
        name: '&fSell Gods Sword'
        commands:
        - item-paywall= item1
        - msg= sold item! (do payment here)
```
